spring:
  application:
    name: test-service
  config:
    import: optional:configserver:http://config-server:8888/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 0