filebeat.inputs:
  - type: container
    paths:
      - "/var/log/containers/*.log"
      - "/var/log/containers/*/*.log"
      - "/var/lib/docker/containers/*.log"
      - "/var/lib/docker/containers/*/*.log"
  - type: filestream
    paths:
      - /usr/share/filebeat/my_logs/*.log
      - /var/log/*.log
  - type: stdin

output.logstash:
  hosts: ["logstash:5044"]