global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "consul-example"
    metrics_path: "/actuator/prometheus"
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - action: keep
        source_labels: [__meta_consul_service]
        regex: consumer
