spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      routes:
        - id: test_service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1
        - id: test_producer
          uri: lb://TEST-PRODUCER
          predicates:
            - Path=/test-producer/**
          filters:
            - StripPrefix=1
        - id: test_consumer
          uri: lb://TEST-CONSUMER
          predicates:
            - Path=/test-consumer/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080

