spring:
  application:
    name: test-consumer
  config:
    import: optional:configserver:http://localhost:8888/
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
